with-expecter: false
packages:
  github.com/mattermost/mattermost/server/v8/einterfaces:
    config:
      all: true
      dir: "einterfaces/mocks"
      filename: "{{.InterfaceName}}.go"
      mockname: "{{.InterfaceName}}"
      outpkg: mocks
      recursive: true
      note: "Regenerate this file using `make einterfaces-mocks`."
