name: Snyk - Software Bill of Materials (SBOM)
on:
  release:
    types: [published]

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: '22.6.0'

      - name: Install Snyk CLI
        run: npm install -g snyk@1.1293.0

      - name: Generate SBOM
        run: snyk sbom --format=cyclonedx1.5+json --all-projects > sbom.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload SBOM
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload "${{ github.event.release.tag_name }}" sbom.json
